### ISSUE TITLE
Sandbox WSDL doesn't seem to exist

### ISSUE THREAD

**Issue by debedb** [yahoojp-marketing/ydn-api-documents#73]
Sandbox WSDL as mentioned for example [here](https://github.com/yahoojp-marketing/ydn-api-documents/blob/master/docs/en/api_reference/services/ReportDefinitionService.md) does not exist at https://sandbox.im.yahooapis.jp/services/V201911/ReportDefinitionService?wsdl

**Comment by xshoji** [comment]
Thank you for your report.
Sandbox environment was already closed in 2020 March, then YDN-API system has been also closed in 2020 December.
Yahoo! JAPAN Ads API is available as migration destination.
Please see details as follows.

> What is Yahoo! JAPAN Ads API  
> https://ads-developers.yahoo.co.jp/developercenter/en/yahoo-ads-api/yahoo-ads-api.html
